### ISSUE TITLE
sorting not working correctly when there is a hidden column

### ISSUE THREAD

**Issue by lyimolucasl** [hermawanramadhan/CodeIgniter4-DataTables#1]
Sorting appears to be out of order when there is a hidden column included.
The sorting order of all columns (excluding the last sortable column in some cases) does not appear to work correctly

You may try it [here in the documentation](https://hermawan.dev/codeigniter4-datatables/usage/hide_column)

**Comment by hermawanramadhan** [comment]
Thanks for reporting the issue. already fix on new version 0.3.1

**Comment by lyimolucasl** [comment]
> Thanks for reporting the issue. already fix on new version 0.3.1
@hermawanramadhan that's awesome
I haven't tried it yet but it's great response
