### ISSUE TITLE
getting error when i'm using join in datatable 

### ISSUE THREAD

**Issue by pateldrishti** [hermawanramadhan/CodeIgniter4-DataTables#14]
**Getting Error : Unknown column 'tbl_`tbl_add_new_feedback.id' in 'field list**
![image](https://user-images.githubusercontent.com/52104443/148776274-ce84ce8e-fec0-4132-b079-c6e757e8b3a3.png)

How to reproduce error :
1) I have used following join query
`$this->db->table('add_new_feedback')->select('add_new_feedback.id as replay_id ,title,status,roadmap.id as roadmap_id ,roadmap.value as status_name')->join('roadmap','roadmap.id = add_new_feedback.status','LEFT');
`
2)  For rest of the code i followed [this link](https://codeigniter4-datatables.hermawan.dev/usage/join_query) 

3) My db settings looks like this
![image](https://user-images.githubusercontent.com/52104443/148775948-a5789352-6980-4f7d-9605-f4dca49f96cc.png)

**Comment by hermawanramadhan** [comment]
please install new version 0.5.3. that's bug come when using DBPrefix, this bug gone on new version.. Thanks for reporting clearly.
