### ISSUE TITLE
Not yet support PHP 8.1

### ISSUE THREAD

**Issue by asnanmtakim** [hermawanramadhan/CodeIgniter4-DataTables#15]
Getting error preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated

**Comment by hermawanramadhan** [comment]
not yet tested on PHP 8.1. Thanks. I'll test and fix later

**Comment by kidando** [comment]
It looks like the package greenlion/PHP-SQL-Parser that this package relies on, is the main issue. It hasn't been updated to support 8.1. It breaks in several areas.

**Comment by hermawanramadhan** [comment]
already updated. Thanks.
