### ISSUE TITLE
Manual Custom queries not working

### ISSUE THREAD

**Issue by navnathsatav** [hermawanramadhan/CodeIgniter4-DataTables#18]
Does this support custom manual queries
e.g. SELECT column1, column2... FROM table1 UNION SELECT column1, column2... FROM table2?
Any solution for this?

**Comment by erikkraijenoord** [comment]
Depends on what driver you are working, with MySQL and i believe in MSSQL you have the VIEW option. This way the query is always done at SQL level, this makes it allot easier to get information from your table.

> [MySQL VIEW](https://dev.mysql.com/doc/refman/8.0/en/create-view.html)
> [MSSQL VIEW](https://docs.microsoft.com/en-us/sql/relational-databases/views/views?view=sql-server-ver15)
> [PostgreSQL VIEW](https://www.postgresql.org/docs/9.2/sql-createview.html)

These are just a few examples on how to approach the issues you are facing, good luck 👍
