### ISSUE TITLE
Unable to update - php version 8.0.5

### ISSUE THREAD

**Issue by lyimolucasl** [hermawanramadhan/CodeIgniter4-DataTables#2]
Problem 1
    - hermawan/codeigniter4-datatables[v0.3.0, ..., v0.3.1] require php ^7.3 -> your php version (8.0.5) does not satisfy that requirement.
    - Root composer.json requires hermawan/codeigniter4-datatables ^0.3.0 -> satisfiable by hermawan/codeigniter4-datatables[v0.3.0, v0.3.1].

**Comment by hermawanramadhan** [comment]
Hi.. sorry..

and not tested on PHP 8. are you already test on php 8 ?  if it will compatible. I will change composer.json

**Comment by lyimolucasl** [comment]
> Hi.. sorry..
> 
> and not tested on PHP 8. are you already test on php 8 ? if it will compatible. I will change composer.json

Yah! I'd love to.

**Comment by hermawanramadhan** [comment]
sorry for late update. already fix now.
