### ISSUE TITLE
Documentation website tables not working

### ISSUE THREAD

**Issue by Rrelio** [hermawanramadhan/CodeIgniter4-DataTables#26]
![Screenshot 2022-09-14 094732](https://user-images.githubusercontent.com/67880242/190040296-8038bd8c-c37d-4371-82f2-69b8e1321c7b.png)

A Datatable alert box keeps popping up. Please fix

**Comment by hermawanramadhan** [comment]
Thanks for info.. already fixed

**Comment by Rrelio** [comment]
Thanks
