### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by ciskhalifa** [hermawanramadhan/CodeIgniter4-DataTables#4]
PHP ver 7.3
Codeigniter ver 4.1.2

Problem 1
    - Root composer.json requires hermawan/codeigniter4-datatables ^0.5.0 -> satisfiable by hermawan/codeigniter4-datatables[v0.5.0].
    - hermawan/codeigniter4-datatables v0.5.0 requires codeigniter4/framework ^4 -> satisfiable by codeigniter4/framework[4.0.0, ..., v4.1.2] from composer repo (https://repo.packagist.org) but codeigniter4/framework[1.0.0+no-version-set] from root package repo has higher repository priority. The packages with higher priority do not match your constraint and are therefore not installable. See https://getcomposer.org/repoprio for details and assistance.

**Comment by hermawanramadhan** [comment]
Do you have any suggestion how should composer.json?

It's look fine here. or maybe I'm not sure what you mean...
