### ISSUE TITLE
Codeigniter 4.1.1

### ISSUE THREAD

**Issue by Nakropol** [hermawanramadhan/CodeIgniter4-DataTables#7]
Which version should I use for Codeigniter 4.1.1?

hermawan/codeigniter4-datatables v0.5.2 requires codeigniter4/framework ^4 -> satisfiable by codeigniter4/framework[v4.0.0-alpha.3, ..., v4.1.3] from composer repo (https://repo.packagist.org) but codeigniter4/framework[dev-main] from root package repo has higher repository priority. The packages with higher priority do not match your constraint and are therefore not installable. See https://getcomposer.org/repoprio for details and assistance.

**Comment by hermawanramadhan** [comment]
latest version should be no problem..

problem with installing? which composer version do you use?
