### ISSUE TITLE
How to use custom filter ?

### ISSUE THREAD

**Issue by jozefrebjak** [hermawanramadhan/CodeIgniter4-DataTables#9]
When I trying to use custom filter as it's described in documentation I am getting 

```js
"title": "ErrorException",
    "type": "ErrorException",
    "code": 500,
    "message": "Undefined property: stdClass::$state",
```

My filter is like:

```php
            ->filter(function ($builder, $request) {
                if ($request->state)
                    $builder->where('customers.state', $request->state);
            })
```

and data function inside ajax like:

```js
data: function (d) {
            d.state = $('#state').val();
}
```

I also have ajax event

```js
$('#state').change(function(event) {
        table.ajax.reload();
    })
```

I cant see HTML example in documentation. Do I need to add someting special to HTML ?

thank you

**Comment by hermawanramadhan** [comment]
$('#state') ==> mean. you can filter with input/select with id="state" . you can learn javascript / jquery first maybe
